spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

application:
  converter:
    maxLength: 8
  baseUrl: http://localhost:8080/
