spring:
  profiles:
    active:
      on-profile: prod
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${JDBC_URL:jdbc:mysql://localhost:3306/url_shortening}
      username: ${JDBC_USERNAME:root}
      password: ${JDBC_PASSWORD:root}
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: SELECT 1
      data-source-properties:
        zeroDateTimeBehavior: convertToNull
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info

application:
  converter:
    maxLength: 8
  baseUrl: ${BASE_URL:http://localhost:8080/}
